// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_getinfo.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_newbook.cpp"
#include "EWIEGA46WW/moc_showallbooks.cpp"
